apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: nomad 
  version: 0.1.0
  annotations:
    categories: nomad
spec:
  displayName: nomad chaos
  categoryDescription: >
    It calls Nomad API to stop and reschedule an allocation for a job 
  faults:
    - name: nomad-stop-alloc
      description: It stop allocations of a Nomad job.
      displayName: "Nomad stop allocation"
  keywords: 
    - "nomad"
  maintainers: 
    - name: huy 
      email: huy.nguyen@adyen.com
  minKubeVersion: 1.12.0 
  provider: 
    name: Adyen
  links: 
    - name: Documentation 
      url: https://docs.litmuschaos.io/docs/getstarted/ 
  icon:
    - url: 
      mediatype: ""
